name: Setup Workflows

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create security-check.yml
        run: |
          mkdir -p .github/workflows
          echo "
          name: Security Check

          on:
            push:
              branches:
                - main
            pull_request:
              branches:
                - main

          jobs:
            security:
              runs-on: ubuntu-latest
              steps:
                - name: Checkout code
                  uses: actions/checkout@v2

                - name: Install dependencies
                  run: npm install

                - name: Run security audit
                  run: npm audit --production
          " > .github/workflows/security-check.yml

      - name: Create ml-model-update.yml
        run: |
          mkdir -p .github/workflows
          echo "
          name: ML Model Update

          on:
            schedule:
              - cron: '0 0 * * 1' # Weekly updates
            workflow_dispatch:

          jobs:
            update-model:
              runs-on: ubuntu-latest
              steps:
                - name: Checkout code
                  uses: actions/checkout@v2

                - name: Set up Python
                  uses: actions/setup-python@v2
                  with:
                    python-version: '3.x'

                - name: Install dependencies
                  run: |
                    python -m pip install --upgrade pip
                    pip install -r requirements.txt

                - name: Update and train model
                  run: python update_model.py
          " > .github/workflows/ml-model-update.yml

      - name: Commit and push workflow files
        uses: EndBug/add-and-commit@v9.1.4
        with:
          author_name: 'GitHub Actions'
          author_email: 'actions@github.com'
          message: 'Add security and ML model update workflows'
          add: '.github/workflows/security-check.yml, .github/workflows/ml-model-update.yml'